# site
# --- editar y ajustar de acuerdo al curso 
site_name: "Del Genoma al Transcriptoma: Fundamentos y Herramientas Informáticas"
site_description: "Sitio Web del Curso Del Genoma al Transcriptoma: Fundamentos y Herramientas Informáticas"
site_author: "UNSAM"
#site_url: https://curso.unsam.edu.ar

# repository
# --- si el sitio está alojado en un repo, describirlo acá 
repo_name: 'cursos-unsam-mkdocs-template'
repo_url: https://github.com/mercedesgarnham/Curso-Omicas-UNSAM

# theme 
# --- customizar apariencia editando palette 
# --- consultar https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
theme:
  name: material
  language: es 
  features:
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - navigation.tabs
    - navigation.indexes
  palette: 
    - scheme: default
      primary: black
      accent: black
      toggle:
        icon: material/toggle-switch 
        name: Cambiar a modo oscuro
    - scheme: slate 
      primary: black
      accent: black
      toggle: 
        icon: material/toggle-switch-off-outline
        name: Cambiar a modo claro

# plugins
plugins:
  - search
  - mkdocs-video 
  - awesome-pages
  #- git-revision-date
  - tags:
      tags_file: tags.md 

# markdown extensions
markdown_extensions:
  - meta
  - admonition
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.mark
  - pymdownx.keys
  - pymdownx.emoji

# extra
# --- editar los URLs, agregar los links especificos a cada cuenta, canal, etc. 
# --- reordenar los bloques de iconos + links de acuerdo al gusto
extra:
  social:
    - icon: fontawesome/brands/slack
      link: https://workspace-name.slack.com
    - icon: fontawesome/brands/github
      link: https://github.com/repo/name
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/cuenta
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/channel/channel-id
    - icon: fontawesome/brands/discord
      link: https://discord.com/server

# extra++
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js

nav:
    - Inicio: 'index.md'
    - Información General: 
        - info/inicio.md
        - Acerca: info/acerca.md
        - Cómo Llegar: info/comollegar.md
        - Programa: info/contenidos.md
        # - Evaluación: info/evaluacion.md 
        # - Cronograma: info/cronograma.md
        - Docentes: info/docentes.md
    - Teoricas: 
        - teoricas/inicio.md
        # - Teórica 1: teoricas/1-Teorica-Uno/index.md
        # - Teórica 2: teoricas/2-Teorica-Dos/index.md
        # - Teórica 3: teoricas/3-Teorica-Tres/index.md
        # - teoricas/resumen.md
    - Practicos: 
        - practicos/inicio.md
        # - TP 1: 'practicos/1-Trabajo-Practico-Uno/index.md'
        # - TP 2: 'practicos/2-Trabajo-Practico-Dos/index.md'
        # - TP 3: 'practicos/3-Trabajo-Practico-Tres/index.md'
        # - practicos/resumen.md
    # - Instructivos:
        # - 'instructivos/instructivos.md'


# copyright
# --- editar y ajustar de acuerdo al curso
copyright: Copyright &copy; 2025 Area Bioinformatica UNSAM
